#!/usr/bin/bash

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

while [ $# -ge 1 ]; do
    case $1 in
        backup)
            iptables-save > "${SCRIPTPATH}/iptables.conf"
            ip6tables-save > "${SCRIPTPATH}/ip6tables.conf"
            ;;

        restore)
            iptables-restore < "${SCRIPTPATH}/iptables.conf"
            ip6tables-restore < "${SCRIPTPATH}/ip6tables.conf"
            ;;

        clear)
            # clear iptables tables
            iptables -P INPUT ACCEPT
            iptables -P FORWARD ACCEPT
            iptables -P OUTPUT ACCEPT

            iptables -Z
            for table in filter nat mangle raw; do
                iptables -t $table -F
                iptables -t $table -X
            done
            ;;

        netedit)
            # Setup DNAT for netedit for locally generated packets
            #
            # Note the PREROUTING chain isn't used as it doesn't apply to locally generated packets.
            #
            # If one wants to do DNAT using the local computer to forward packets (which also requires the PREROUTING chain), enable ip forwarding:
            # $ sysctl net.ipv4.conf.<interface>.forwarding=1
            #
            # Redirect packets generated by local interface to netedit, avoiding redirecting netedit back to itself
            iptables -t nat -I OUTPUT -p tcp ! --sport 11110 --dport 80 -j REDIRECT --to-ports 11110
            iptables -t nat -L -n -v
            ;;

        list)
            iptables-save
            ;;

        help)
            ;&
        *)
            echo "iptables.sh clear|netedit|backup|list"
            ;;
    esac

    shift
done
