# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: ssh into server
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          GITHUB_BRANCH: ${{ github.ref }}
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -T -o StrictHostKeyChecking=no "root@$HOST" -i ~/.ssh/id_rsa <<EOF

          # Update repository
          mkdir -p "/www/infinite-closet/${GITHUB_BRANCH##*/}"
          cd "/www/infinite-closet/${GITHUB_BRANCH##*/}"
          git swtich "${GITHUB_BRANCH##*/}"
          git fetch --all
          git pull origin "${GITHUB_BRANCH##*/}"

          if [[ $? -ne 0 ]]; then
            echo Failed to pull origin "${GITHUB_BRANCH##*/}"
            exit 1
          fi

          # Build website with expo
          (
            set -e
            cd frontend
            yarn install
            expo build:web
          ) &

          (
            set -e
            cd backend
            npx strapi build
            nohup npx strapi start
          ) &

          EOF

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
