name: server
version: 0.1.0.0
github: "githubuser/server"
license: BSD3
author: "Trey Wilkinson"
maintainer: "winston.trey.wilkinson@gmail.com"
copyright: "2020 Trey Wilkinson"

default-extensions:
  - OverloadedStrings
  - TypeOperators

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      # Internal
      - blog
      - dogwalking
      # - studio
      - elders
      # External
      - acid-state
      - bytestring
      - servant
      - servant-options
      - servant-server
      - server
      - tagged
      - wai
      - wai-cors
      - wai-extra
      - wai-make-assets
      - warp
      - warp-tls
      - streaming-commons
      - network
      - text

  server-gen-exe:
    source-dirs: gen
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - blog
      - dogwalking
      # - studio
      - elders
