version: '3.3'

services:
  client: &client
    image: node:16-alpine
    env_file: .env
    volumes:
      - type: bind
        source: ./client
        target: /app
    working_dir: /app
    build:
      context: ./client
    environment:
      - NODE_ENV
    ports:
      - "127.0.0.1:3000:3000"
    command: yarn run dev --host

  client-dev:
    <<: *client
    command: yarn run dev --host

  server:
    image: node:16-alpine
    env_file: .env
    volumes:
      - type: bind
        source: ./server
        target: /app
    working_dir: /app
    build:
      context: ./server
    environment:
      - NODE_ENV
      - DATABASE_HOST
      - DATABASE_NAME
      - DATABASE_PORT
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
    ports:
      - "127.0.0.1:1337:1337"
    command: yarn run develop

  # db:
  #   image: postgres:13-alpine
  #   env_file: .env
  #   environment:
  #     POSTGRES_DB: ysa-website-dev
  #     POSTGRES_USER: test
  #     POSTGRES_PASSWORD: test
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   ports:
  #     - "127.0.0.1:5433:5432"

volumes:
  postgres:
