#!/bin/bash
# Flatten {directory} and move it to a tmp {directory} to make it easier to upload filenames
# Especially useful for gemini as it requires unique file names

TARGET_DIR="${1:-.}"

if [ ! -d "$TARGET_DIR" ]; then
  echo "Error: ${TARGET_DIR} is not a valid directory"
  exit 1
fi

cd "$TARGET_DIR" || exit

OS_TYPE="$(uname)"

if [ "$OS_TYPE" = "Darwin" ]; then
  DEST_DIR="$HOME/Library/Caches/flatten/$(basename $PWD)"
else
  DEST_DIR="$HOME/.cache/flatten/$(basename $PWD)"
fi

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"

# Find all files recursively (-type f)
# -print0 and IFS= read -r -d '' handles filenames with spaces safely
find . -type f -not -path '*/.*' -not -path '*node_modules*' -print0 | while IFS= read -r -d '' file; do

  # ./dir1/file.txt -> dir1/file.txt
  clean_path="${file#./}"

  # Replace all slashes (/) with dashes (-)
  new_name="${clean_path//\//-}"

  # Copy the file to the destination
  if [ "$OS_TYPE" = "Darwin" ]; then
    # cp "$PWD/$clean_path" "$DEST_DIR/$new_name"
    ln -sf "$PWD/$clean_path" "$DEST_DIR/$new_name"
  else
    ln -sf "$PWD/$clean_path" "$DEST_DIR/$new_name"
  fi

done

echo "$DEST_DIR"
